In [1]:
import glob
import pandas
import seaborn as sns
import matplotlib.pyplot as plt, mpld3
import plotly.graph_objects as go

In [2]:
path_datasets_dir = r'./datasets'
path_datasets_files = glob.glob(path_datasets_dir + "/*.csv")
path_datasets_files

['./datasets/2022-06-05.csv',
 './datasets/2022-06-08.csv',
 './datasets/2022-06-09.csv',
 './datasets/2022-06-04.csv',
 './datasets/2022-06-03.csv',
 './datasets/2022-06-07.csv',
 './datasets/2022-06-06.csv',
 './datasets/2022-06-10.csv']

In [3]:
dfs = []

for path_datasets_file in path_datasets_files:
    df_temp = pandas.read_csv(path_datasets_file)
    dfs.append(df_temp)

df = pandas.concat(dfs)
df = df.sort_values('current_date')
df

,Unnamed: 0,current_date,category_id,category_name,subcategory_id,subcategory_name,product_id,product_name,price_unit,price_bulk,price_iva
1,1,2022-06-03,12,"Aceite, especias y salsas",112,"Aceite, vinagre y sal",19715.0,Sal de mesa Hacendado,0.38,1.52,10
2317,2317,2022-06-03,4,Charcutería y quesos,50,Jamón serrano,58278.0,Jamón cebo ibérico cortado a cuchillo,5.85,65.00,10
2318,2318,2022-06-03,4,Charcutería y quesos,50,Jamón serrano,58280.0,Jamón bellota ibérico cortado a cuchillo,11.25,125.00,10
2319,2319,2022-06-03,4,Charcutería y quesos,50,Jamón serrano,59173.0,Paleta curada lonchas Paletas Marpa,3.14,13.08,10
2320,2320,2022-06-03,4,Charcutería y quesos,50,Jamón serrano,58230.0,Surtido de ibéricos La Hacienda del ibérico,5.95,29.75,10
...,...,...,...,...,...,...,...,...,...,...,...
2318,2318,2022-06-10,4,Charcutería y quesos,50,Jamón serrano,58280.0,Jamón bellota ibérico cortado a cuchillo,11.25,125.00,10
2317,2317,2022-06-10,4,Charcutería y quesos,50,Jamón serrano,58278.0,Jamón cebo ibérico cortado a cuchillo,5.85,65.00,10
2316,2316,2022-06-10,4,Charcutería y quesos,50,Jamón serrano,58110.0,Jamón serrano Incarlopsa,32.00,4.76,10
2327,2327,2022-06-10,4,Charcutería y quesos,58,Paté y sobrasada,52337.0,Paté de anchoa y salmón Hacendado,0.84,5.25,10
6970,6970,2022-06-10,10,Zumos,98,Tomate y otros sabores,39390.0,Zumo de tomate picante Big Tom,1.65,6.60,10

In [4]:
path_graphs_dir = r'./graphs'

categories_ids = df.category_id.unique()

for category_id in categories_ids:
    df_category = df[df.category_id == category_id]
    category_name = df_category.category_name.iloc[0]
    products_ids = df_category.product_id.unique()

    fig = go.Figure()

    for product_id in products_ids:
        df_product = df[df.product_id == product_id]
        product_name = df_product.product_name.iloc[0]

        x = df_product.current_date
        y = df_product.price_unit
        fig.add_trace( go.Scatter( x=x, y=y, mode='lines+markers', name= f"{product_id}_{product_name}" ) )

    fig.write_html(f"{path_graphs_dir}/{category_name}.html")